version: "3.2"

services:
  envoy:
    image: envoyproxy/envoy:v1.17.0
    network_mode: host # ativar se estiver no linux
    restart: always
    # ports:  # ativar se estiver no Windows ou Mac
    #   - "8080:8080"
    #   - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
